---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dws-cray-hpe-com-v1alpha3-desert
  failurePolicy: Fail
  name: mdesert.kb.io
  rules:
  - apiGroups:
    - dws.cray.hpe.com
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - deserts
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dws-cray-hpe-com-v1alpha3-desert
  failurePolicy: Fail
  name: vdesert.kb.io
  rules:
  - apiGroups:
    - dws.cray.hpe.com
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - deserts
  sideEffects: None
