//go:build !ignore_autogenerated_core
// +build !ignore_autogenerated_core

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha2 "github.com/roehrich-hpe/multiversion-crd-play/api/v1alpha2"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Desert)(nil), (*v1alpha2.Desert)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Desert_To_v1alpha2_Desert(a.(*Desert), b.(*v1alpha2.Desert), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Desert)(nil), (*Desert)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Desert_To_v1alpha1_Desert(a.(*v1alpha2.Desert), b.(*Desert), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DesertList)(nil), (*v1alpha2.DesertList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DesertList_To_v1alpha2_DesertList(a.(*DesertList), b.(*v1alpha2.DesertList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.DesertList)(nil), (*DesertList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_DesertList_To_v1alpha1_DesertList(a.(*v1alpha2.DesertList), b.(*DesertList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DesertSpec)(nil), (*v1alpha2.DesertSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DesertSpec_To_v1alpha2_DesertSpec(a.(*DesertSpec), b.(*v1alpha2.DesertSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DesertStatus)(nil), (*v1alpha2.DesertStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DesertStatus_To_v1alpha2_DesertStatus(a.(*DesertStatus), b.(*v1alpha2.DesertStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.DesertStatus)(nil), (*DesertStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_DesertStatus_To_v1alpha1_DesertStatus(a.(*v1alpha2.DesertStatus), b.(*DesertStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Vehicle)(nil), (*v1alpha2.Vehicle)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Vehicle_To_v1alpha2_Vehicle(a.(*Vehicle), b.(*v1alpha2.Vehicle), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Vehicle)(nil), (*Vehicle)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Vehicle_To_v1alpha1_Vehicle(a.(*v1alpha2.Vehicle), b.(*Vehicle), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VehicleList)(nil), (*v1alpha2.VehicleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VehicleList_To_v1alpha2_VehicleList(a.(*VehicleList), b.(*v1alpha2.VehicleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.VehicleList)(nil), (*VehicleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VehicleList_To_v1alpha1_VehicleList(a.(*v1alpha2.VehicleList), b.(*VehicleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VehicleSpec)(nil), (*v1alpha2.VehicleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VehicleSpec_To_v1alpha2_VehicleSpec(a.(*VehicleSpec), b.(*v1alpha2.VehicleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.VehicleSpec)(nil), (*VehicleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VehicleSpec_To_v1alpha1_VehicleSpec(a.(*v1alpha2.VehicleSpec), b.(*VehicleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VehicleStatus)(nil), (*v1alpha2.VehicleStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VehicleStatus_To_v1alpha2_VehicleStatus(a.(*VehicleStatus), b.(*v1alpha2.VehicleStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.DesertSpec)(nil), (*DesertSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_DesertSpec_To_v1alpha1_DesertSpec(a.(*v1alpha2.DesertSpec), b.(*DesertSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.VehicleStatus)(nil), (*VehicleStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VehicleStatus_To_v1alpha1_VehicleStatus(a.(*v1alpha2.VehicleStatus), b.(*VehicleStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Desert_To_v1alpha2_Desert(in *Desert, out *v1alpha2.Desert, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DesertSpec_To_v1alpha2_DesertSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DesertStatus_To_v1alpha2_DesertStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Desert_To_v1alpha2_Desert is an autogenerated conversion function.
func Convert_v1alpha1_Desert_To_v1alpha2_Desert(in *Desert, out *v1alpha2.Desert, s conversion.Scope) error {
	return autoConvert_v1alpha1_Desert_To_v1alpha2_Desert(in, out, s)
}

func autoConvert_v1alpha2_Desert_To_v1alpha1_Desert(in *v1alpha2.Desert, out *Desert, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_DesertSpec_To_v1alpha1_DesertSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_DesertStatus_To_v1alpha1_DesertStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_Desert_To_v1alpha1_Desert is an autogenerated conversion function.
func Convert_v1alpha2_Desert_To_v1alpha1_Desert(in *v1alpha2.Desert, out *Desert, s conversion.Scope) error {
	return autoConvert_v1alpha2_Desert_To_v1alpha1_Desert(in, out, s)
}

func autoConvert_v1alpha1_DesertList_To_v1alpha2_DesertList(in *DesertList, out *v1alpha2.DesertList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.Desert, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Desert_To_v1alpha2_Desert(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_DesertList_To_v1alpha2_DesertList is an autogenerated conversion function.
func Convert_v1alpha1_DesertList_To_v1alpha2_DesertList(in *DesertList, out *v1alpha2.DesertList, s conversion.Scope) error {
	return autoConvert_v1alpha1_DesertList_To_v1alpha2_DesertList(in, out, s)
}

func autoConvert_v1alpha2_DesertList_To_v1alpha1_DesertList(in *v1alpha2.DesertList, out *DesertList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Desert, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_Desert_To_v1alpha1_Desert(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_DesertList_To_v1alpha1_DesertList is an autogenerated conversion function.
func Convert_v1alpha2_DesertList_To_v1alpha1_DesertList(in *v1alpha2.DesertList, out *DesertList, s conversion.Scope) error {
	return autoConvert_v1alpha2_DesertList_To_v1alpha1_DesertList(in, out, s)
}

func autoConvert_v1alpha1_DesertSpec_To_v1alpha2_DesertSpec(in *DesertSpec, out *v1alpha2.DesertSpec, s conversion.Scope) error {
	out.Foo = in.Foo
	out.Type = in.Type
	out.Traveler = in.Traveler
	return nil
}

// Convert_v1alpha1_DesertSpec_To_v1alpha2_DesertSpec is an autogenerated conversion function.
func Convert_v1alpha1_DesertSpec_To_v1alpha2_DesertSpec(in *DesertSpec, out *v1alpha2.DesertSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DesertSpec_To_v1alpha2_DesertSpec(in, out, s)
}

func autoConvert_v1alpha2_DesertSpec_To_v1alpha1_DesertSpec(in *v1alpha2.DesertSpec, out *DesertSpec, s conversion.Scope) error {
	out.Foo = in.Foo
	out.Type = in.Type
	out.Traveler = in.Traveler
	// WARNING: in.Days requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_DesertStatus_To_v1alpha2_DesertStatus(in *DesertStatus, out *v1alpha2.DesertStatus, s conversion.Scope) error {
	out.Traveler = in.Traveler
	out.WaterLevel = in.WaterLevel
	return nil
}

// Convert_v1alpha1_DesertStatus_To_v1alpha2_DesertStatus is an autogenerated conversion function.
func Convert_v1alpha1_DesertStatus_To_v1alpha2_DesertStatus(in *DesertStatus, out *v1alpha2.DesertStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_DesertStatus_To_v1alpha2_DesertStatus(in, out, s)
}

func autoConvert_v1alpha2_DesertStatus_To_v1alpha1_DesertStatus(in *v1alpha2.DesertStatus, out *DesertStatus, s conversion.Scope) error {
	out.Traveler = in.Traveler
	out.WaterLevel = in.WaterLevel
	return nil
}

// Convert_v1alpha2_DesertStatus_To_v1alpha1_DesertStatus is an autogenerated conversion function.
func Convert_v1alpha2_DesertStatus_To_v1alpha1_DesertStatus(in *v1alpha2.DesertStatus, out *DesertStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_DesertStatus_To_v1alpha1_DesertStatus(in, out, s)
}

func autoConvert_v1alpha1_Vehicle_To_v1alpha2_Vehicle(in *Vehicle, out *v1alpha2.Vehicle, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VehicleSpec_To_v1alpha2_VehicleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VehicleStatus_To_v1alpha2_VehicleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Vehicle_To_v1alpha2_Vehicle is an autogenerated conversion function.
func Convert_v1alpha1_Vehicle_To_v1alpha2_Vehicle(in *Vehicle, out *v1alpha2.Vehicle, s conversion.Scope) error {
	return autoConvert_v1alpha1_Vehicle_To_v1alpha2_Vehicle(in, out, s)
}

func autoConvert_v1alpha2_Vehicle_To_v1alpha1_Vehicle(in *v1alpha2.Vehicle, out *Vehicle, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_VehicleSpec_To_v1alpha1_VehicleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_VehicleStatus_To_v1alpha1_VehicleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_Vehicle_To_v1alpha1_Vehicle is an autogenerated conversion function.
func Convert_v1alpha2_Vehicle_To_v1alpha1_Vehicle(in *v1alpha2.Vehicle, out *Vehicle, s conversion.Scope) error {
	return autoConvert_v1alpha2_Vehicle_To_v1alpha1_Vehicle(in, out, s)
}

func autoConvert_v1alpha1_VehicleList_To_v1alpha2_VehicleList(in *VehicleList, out *v1alpha2.VehicleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.Vehicle, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Vehicle_To_v1alpha2_Vehicle(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_VehicleList_To_v1alpha2_VehicleList is an autogenerated conversion function.
func Convert_v1alpha1_VehicleList_To_v1alpha2_VehicleList(in *VehicleList, out *v1alpha2.VehicleList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VehicleList_To_v1alpha2_VehicleList(in, out, s)
}

func autoConvert_v1alpha2_VehicleList_To_v1alpha1_VehicleList(in *v1alpha2.VehicleList, out *VehicleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Vehicle, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_Vehicle_To_v1alpha1_Vehicle(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_VehicleList_To_v1alpha1_VehicleList is an autogenerated conversion function.
func Convert_v1alpha2_VehicleList_To_v1alpha1_VehicleList(in *v1alpha2.VehicleList, out *VehicleList, s conversion.Scope) error {
	return autoConvert_v1alpha2_VehicleList_To_v1alpha1_VehicleList(in, out, s)
}

func autoConvert_v1alpha1_VehicleSpec_To_v1alpha2_VehicleSpec(in *VehicleSpec, out *v1alpha2.VehicleSpec, s conversion.Scope) error {
	out.Foo = in.Foo
	out.Make = in.Make
	return nil
}

// Convert_v1alpha1_VehicleSpec_To_v1alpha2_VehicleSpec is an autogenerated conversion function.
func Convert_v1alpha1_VehicleSpec_To_v1alpha2_VehicleSpec(in *VehicleSpec, out *v1alpha2.VehicleSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VehicleSpec_To_v1alpha2_VehicleSpec(in, out, s)
}

func autoConvert_v1alpha2_VehicleSpec_To_v1alpha1_VehicleSpec(in *v1alpha2.VehicleSpec, out *VehicleSpec, s conversion.Scope) error {
	out.Foo = in.Foo
	out.Make = in.Make
	return nil
}

// Convert_v1alpha2_VehicleSpec_To_v1alpha1_VehicleSpec is an autogenerated conversion function.
func Convert_v1alpha2_VehicleSpec_To_v1alpha1_VehicleSpec(in *v1alpha2.VehicleSpec, out *VehicleSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_VehicleSpec_To_v1alpha1_VehicleSpec(in, out, s)
}

func autoConvert_v1alpha1_VehicleStatus_To_v1alpha2_VehicleStatus(in *VehicleStatus, out *v1alpha2.VehicleStatus, s conversion.Scope) error {
	out.Make = in.Make
	return nil
}

// Convert_v1alpha1_VehicleStatus_To_v1alpha2_VehicleStatus is an autogenerated conversion function.
func Convert_v1alpha1_VehicleStatus_To_v1alpha2_VehicleStatus(in *VehicleStatus, out *v1alpha2.VehicleStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VehicleStatus_To_v1alpha2_VehicleStatus(in, out, s)
}

func autoConvert_v1alpha2_VehicleStatus_To_v1alpha1_VehicleStatus(in *v1alpha2.VehicleStatus, out *VehicleStatus, s conversion.Scope) error {
	out.Make = in.Make
	// WARNING: in.Tires requires manual conversion: does not exist in peer-type
	return nil
}
