//go:build !ignore_autogenerated_core
// +build !ignore_autogenerated_core

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha3 "github.com/roehrich-hpe/multiversion-crd-play/api/v1alpha3"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Desert)(nil), (*v1alpha3.Desert)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Desert_To_v1alpha3_Desert(a.(*Desert), b.(*v1alpha3.Desert), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.Desert)(nil), (*Desert)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_Desert_To_v1alpha2_Desert(a.(*v1alpha3.Desert), b.(*Desert), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DesertList)(nil), (*v1alpha3.DesertList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_DesertList_To_v1alpha3_DesertList(a.(*DesertList), b.(*v1alpha3.DesertList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.DesertList)(nil), (*DesertList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DesertList_To_v1alpha2_DesertList(a.(*v1alpha3.DesertList), b.(*DesertList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DesertSpec)(nil), (*v1alpha3.DesertSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_DesertSpec_To_v1alpha3_DesertSpec(a.(*DesertSpec), b.(*v1alpha3.DesertSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DesertStatus)(nil), (*v1alpha3.DesertStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_DesertStatus_To_v1alpha3_DesertStatus(a.(*DesertStatus), b.(*v1alpha3.DesertStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.DesertStatus)(nil), (*DesertStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DesertStatus_To_v1alpha2_DesertStatus(a.(*v1alpha3.DesertStatus), b.(*DesertStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Vehicle)(nil), (*v1alpha3.Vehicle)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Vehicle_To_v1alpha3_Vehicle(a.(*Vehicle), b.(*v1alpha3.Vehicle), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.Vehicle)(nil), (*Vehicle)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_Vehicle_To_v1alpha2_Vehicle(a.(*v1alpha3.Vehicle), b.(*Vehicle), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VehicleList)(nil), (*v1alpha3.VehicleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VehicleList_To_v1alpha3_VehicleList(a.(*VehicleList), b.(*v1alpha3.VehicleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.VehicleList)(nil), (*VehicleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VehicleList_To_v1alpha2_VehicleList(a.(*v1alpha3.VehicleList), b.(*VehicleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VehicleSpec)(nil), (*v1alpha3.VehicleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VehicleSpec_To_v1alpha3_VehicleSpec(a.(*VehicleSpec), b.(*v1alpha3.VehicleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.VehicleSpec)(nil), (*VehicleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VehicleSpec_To_v1alpha2_VehicleSpec(a.(*v1alpha3.VehicleSpec), b.(*VehicleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VehicleStatus)(nil), (*v1alpha3.VehicleStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VehicleStatus_To_v1alpha3_VehicleStatus(a.(*VehicleStatus), b.(*v1alpha3.VehicleStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha3.DesertSpec)(nil), (*DesertSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DesertSpec_To_v1alpha2_DesertSpec(a.(*v1alpha3.DesertSpec), b.(*DesertSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha3.VehicleStatus)(nil), (*VehicleStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VehicleStatus_To_v1alpha2_VehicleStatus(a.(*v1alpha3.VehicleStatus), b.(*VehicleStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha2_Desert_To_v1alpha3_Desert(in *Desert, out *v1alpha3.Desert, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_DesertSpec_To_v1alpha3_DesertSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_DesertStatus_To_v1alpha3_DesertStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_Desert_To_v1alpha3_Desert is an autogenerated conversion function.
func Convert_v1alpha2_Desert_To_v1alpha3_Desert(in *Desert, out *v1alpha3.Desert, s conversion.Scope) error {
	return autoConvert_v1alpha2_Desert_To_v1alpha3_Desert(in, out, s)
}

func autoConvert_v1alpha3_Desert_To_v1alpha2_Desert(in *v1alpha3.Desert, out *Desert, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_DesertSpec_To_v1alpha2_DesertSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_DesertStatus_To_v1alpha2_DesertStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_Desert_To_v1alpha2_Desert is an autogenerated conversion function.
func Convert_v1alpha3_Desert_To_v1alpha2_Desert(in *v1alpha3.Desert, out *Desert, s conversion.Scope) error {
	return autoConvert_v1alpha3_Desert_To_v1alpha2_Desert(in, out, s)
}

func autoConvert_v1alpha2_DesertList_To_v1alpha3_DesertList(in *DesertList, out *v1alpha3.DesertList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha3.Desert, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_Desert_To_v1alpha3_Desert(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_DesertList_To_v1alpha3_DesertList is an autogenerated conversion function.
func Convert_v1alpha2_DesertList_To_v1alpha3_DesertList(in *DesertList, out *v1alpha3.DesertList, s conversion.Scope) error {
	return autoConvert_v1alpha2_DesertList_To_v1alpha3_DesertList(in, out, s)
}

func autoConvert_v1alpha3_DesertList_To_v1alpha2_DesertList(in *v1alpha3.DesertList, out *DesertList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Desert, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_Desert_To_v1alpha2_Desert(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_DesertList_To_v1alpha2_DesertList is an autogenerated conversion function.
func Convert_v1alpha3_DesertList_To_v1alpha2_DesertList(in *v1alpha3.DesertList, out *DesertList, s conversion.Scope) error {
	return autoConvert_v1alpha3_DesertList_To_v1alpha2_DesertList(in, out, s)
}

func autoConvert_v1alpha2_DesertSpec_To_v1alpha3_DesertSpec(in *DesertSpec, out *v1alpha3.DesertSpec, s conversion.Scope) error {
	out.Foo = in.Foo
	out.Type = in.Type
	out.Traveler = in.Traveler
	out.Days = in.Days
	return nil
}

// Convert_v1alpha2_DesertSpec_To_v1alpha3_DesertSpec is an autogenerated conversion function.
func Convert_v1alpha2_DesertSpec_To_v1alpha3_DesertSpec(in *DesertSpec, out *v1alpha3.DesertSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_DesertSpec_To_v1alpha3_DesertSpec(in, out, s)
}

func autoConvert_v1alpha3_DesertSpec_To_v1alpha2_DesertSpec(in *v1alpha3.DesertSpec, out *DesertSpec, s conversion.Scope) error {
	out.Foo = in.Foo
	out.Type = in.Type
	out.Traveler = in.Traveler
	out.Days = in.Days
	// WARNING: in.Tool requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha2_DesertStatus_To_v1alpha3_DesertStatus(in *DesertStatus, out *v1alpha3.DesertStatus, s conversion.Scope) error {
	out.Traveler = in.Traveler
	out.WaterLevel = in.WaterLevel
	return nil
}

// Convert_v1alpha2_DesertStatus_To_v1alpha3_DesertStatus is an autogenerated conversion function.
func Convert_v1alpha2_DesertStatus_To_v1alpha3_DesertStatus(in *DesertStatus, out *v1alpha3.DesertStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_DesertStatus_To_v1alpha3_DesertStatus(in, out, s)
}

func autoConvert_v1alpha3_DesertStatus_To_v1alpha2_DesertStatus(in *v1alpha3.DesertStatus, out *DesertStatus, s conversion.Scope) error {
	out.Traveler = in.Traveler
	out.WaterLevel = in.WaterLevel
	return nil
}

// Convert_v1alpha3_DesertStatus_To_v1alpha2_DesertStatus is an autogenerated conversion function.
func Convert_v1alpha3_DesertStatus_To_v1alpha2_DesertStatus(in *v1alpha3.DesertStatus, out *DesertStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_DesertStatus_To_v1alpha2_DesertStatus(in, out, s)
}

func autoConvert_v1alpha2_Vehicle_To_v1alpha3_Vehicle(in *Vehicle, out *v1alpha3.Vehicle, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_VehicleSpec_To_v1alpha3_VehicleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_VehicleStatus_To_v1alpha3_VehicleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_Vehicle_To_v1alpha3_Vehicle is an autogenerated conversion function.
func Convert_v1alpha2_Vehicle_To_v1alpha3_Vehicle(in *Vehicle, out *v1alpha3.Vehicle, s conversion.Scope) error {
	return autoConvert_v1alpha2_Vehicle_To_v1alpha3_Vehicle(in, out, s)
}

func autoConvert_v1alpha3_Vehicle_To_v1alpha2_Vehicle(in *v1alpha3.Vehicle, out *Vehicle, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_VehicleSpec_To_v1alpha2_VehicleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_VehicleStatus_To_v1alpha2_VehicleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_Vehicle_To_v1alpha2_Vehicle is an autogenerated conversion function.
func Convert_v1alpha3_Vehicle_To_v1alpha2_Vehicle(in *v1alpha3.Vehicle, out *Vehicle, s conversion.Scope) error {
	return autoConvert_v1alpha3_Vehicle_To_v1alpha2_Vehicle(in, out, s)
}

func autoConvert_v1alpha2_VehicleList_To_v1alpha3_VehicleList(in *VehicleList, out *v1alpha3.VehicleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha3.Vehicle, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_Vehicle_To_v1alpha3_Vehicle(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_VehicleList_To_v1alpha3_VehicleList is an autogenerated conversion function.
func Convert_v1alpha2_VehicleList_To_v1alpha3_VehicleList(in *VehicleList, out *v1alpha3.VehicleList, s conversion.Scope) error {
	return autoConvert_v1alpha2_VehicleList_To_v1alpha3_VehicleList(in, out, s)
}

func autoConvert_v1alpha3_VehicleList_To_v1alpha2_VehicleList(in *v1alpha3.VehicleList, out *VehicleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Vehicle, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_Vehicle_To_v1alpha2_Vehicle(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_VehicleList_To_v1alpha2_VehicleList is an autogenerated conversion function.
func Convert_v1alpha3_VehicleList_To_v1alpha2_VehicleList(in *v1alpha3.VehicleList, out *VehicleList, s conversion.Scope) error {
	return autoConvert_v1alpha3_VehicleList_To_v1alpha2_VehicleList(in, out, s)
}

func autoConvert_v1alpha2_VehicleSpec_To_v1alpha3_VehicleSpec(in *VehicleSpec, out *v1alpha3.VehicleSpec, s conversion.Scope) error {
	out.Foo = in.Foo
	out.Make = in.Make
	return nil
}

// Convert_v1alpha2_VehicleSpec_To_v1alpha3_VehicleSpec is an autogenerated conversion function.
func Convert_v1alpha2_VehicleSpec_To_v1alpha3_VehicleSpec(in *VehicleSpec, out *v1alpha3.VehicleSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_VehicleSpec_To_v1alpha3_VehicleSpec(in, out, s)
}

func autoConvert_v1alpha3_VehicleSpec_To_v1alpha2_VehicleSpec(in *v1alpha3.VehicleSpec, out *VehicleSpec, s conversion.Scope) error {
	out.Foo = in.Foo
	out.Make = in.Make
	return nil
}

// Convert_v1alpha3_VehicleSpec_To_v1alpha2_VehicleSpec is an autogenerated conversion function.
func Convert_v1alpha3_VehicleSpec_To_v1alpha2_VehicleSpec(in *v1alpha3.VehicleSpec, out *VehicleSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_VehicleSpec_To_v1alpha2_VehicleSpec(in, out, s)
}

func autoConvert_v1alpha2_VehicleStatus_To_v1alpha3_VehicleStatus(in *VehicleStatus, out *v1alpha3.VehicleStatus, s conversion.Scope) error {
	out.Make = in.Make
	out.Tires = in.Tires
	return nil
}

// Convert_v1alpha2_VehicleStatus_To_v1alpha3_VehicleStatus is an autogenerated conversion function.
func Convert_v1alpha2_VehicleStatus_To_v1alpha3_VehicleStatus(in *VehicleStatus, out *v1alpha3.VehicleStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_VehicleStatus_To_v1alpha3_VehicleStatus(in, out, s)
}

func autoConvert_v1alpha3_VehicleStatus_To_v1alpha2_VehicleStatus(in *v1alpha3.VehicleStatus, out *VehicleStatus, s conversion.Scope) error {
	out.Make = in.Make
	out.Tires = in.Tires
	return nil
}
